# Generated by Django 2.1.11 on 2019-10-20 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('message', models.CharField(max_length=140)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('votes', models.IntegerField(default=1)),
            ],
        ),
    ]
